@startuml settings

class Setting {
    +Setting(int min, int max)
    +void set(int value);
    +void increment();
    +void decrement();
    +int get()
    -int value
    -int max
    -int min
}

class Settings {
    +void addSetting(std::string name, Setting& setting)
    +Setting &getSetting(std::string name) const;
    -std::map<std::string, Setting> settingsMap
}


Setting "many" --* Settings


@enduml